name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    if: github.event.ref_type == 'tag' && startsWith(github.event.ref, 'v')
    runs-on: ubuntu-latest

    steps:
      - name: Get the version
        id: get_version
        run: |
          echo "event-name: ${{ github.event_name }}"
          echo $VERSION_REF
          echo "VERSION=${VERSION_REF/refs\/tags\/\v}" >> $GITHUB_OUTPUT
        env:
          VERSION_REF: ${{ github.ref }}

      - name: log
        run: |
          echo ${{ steps.get_version.outputs.VERSION }}