name: CI

on:
  create:

jobs:
  deploy:
    if: github.event_name == 'create' && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Get the version
        id: get_version
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github_ref_type: ${{ github.ref_type }}"
          echo "github.ref: ${{ github.ref }}"
          echo $VERSION_REF
          echo "VERSION=${VERSION_REF/refs\/tags\/\v}" >> $GITHUB_OUTPUT
        env:
          VERSION_REF: ${{ github.ref }}

      - name: log
        run: |
          echo ${{ steps.get_version.outputs.VERSION }}